GSSOC'24 Issue #979 - Adding PDF Utility Tool to Python in Basics in …
Kushal997-das/Project-Guidance pull request #1011
Opened 2024-05-13 07:16 UTC by KJ173

…Desktop Applications

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

I have added 'PDF Utility Tool' in Python under Basics in Desktop Applications.
This tool allows 4 functions:
-> Merge Selected PDFs and save it in desired location
-> Convert a PDF to .docx file
-> Password protect a pdf file
-> Split pdf based on page number into 2 pdfs
This helps to perform PDF manipulations offline for free, instead of uploading sensitive documents on the cloud on random websites.
![image](https://github.com/Kushal997-das/Project-Guidance/assets/92749776/f06cab57-86da-4313-bde8-93ff4f547a9c)

Fixes #979 

### Checklist

- [ yes ] I've read the contribution guidelines.
- [ yes ] I've checked the issue list before deciding what to submit.
- [ yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
GSSOC'24 Issue #979

2024-05-16 03:32 UTC, Kushal997-das requested changes
@KJ173 You have to add good `readme.md` file and make sure your image should work

2024-05-16 03:32 UTC, Kushal997-das commented on Desktop Application/Basic/Python/PDF Utility Tool/readme.md
> +![1715583384233](image/readme/1715583384233.png "GUI Interface")
Image is not working.

2024-05-23 16:46 UTC, Kushal997-das commented
@KJ173 Update on this ?

2024-05-23 18:59 UTC, KJ173 commented
> @KJ173 Update on this ?

Will be updating it by tomorrow. Till then please assign labels as gssoc and level as well.
thank you!

2024-05-26 10:50 UTC, KJ173 commented
@Kushal997-das Hi I have made the required changes. Please add tags and accept the pull request.
Thank you!

2024-05-29 06:11 UTC, Kushal997-das requested changes
@KJ173 Kindly add your project under python basic [here](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md)

2024-05-29 11:57 UTC, KJ173 commented
> @KJ173 Kindly add your project under python basic [here](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md)

Have added the project in this index. Kindly review and merge the commits. 
Thank you!

2024-05-30 04:33 UTC, Kushal997-das approved these changes
@KJ173 💯

2024-05-30 04:34 UTC, merged