Added a calorie burnt prediction model
Kushal997-das/Project-Guidance pull request #1039
Opened 2024-05-16 09:03 UTC by Seersha9802

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes

### Description

Adding this project to Basic section of Data Science and Machine Learning folder with main folder name as "Calorie Burnt Prediction". The project is done in a Jupyter Notebook and python libraries like pandas, numpy, matplotlib and seaborn are used for visualizations and XGBoost for prediction.

Fixes #989 

### Checklist

- [✔️ ] I've read the contribution guidelines.
- [✔️ ] I've checked the issue list before deciding what to submit.
- [✔️ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This is the related PR and the issue fixed is https://github.com/Kushal997-das/Project-Guidance/issues/989

2024-05-20 04:10 UTC, Kushal997-das requested changes
@Seersha9802 Things you need to change :
1. Add good images in `readme.md` file also add good description about your project like how to use? what exactly the project is about everything you need to mention.
2. Create a folder called `dataset` add your `.csv` file over there.

2024-05-20 04:10 UTC, Kushal997-das commented on Machine Learning and Data Science/Basic/Calorie Burnt Prediction/README.md
> +The following project deals with datasets of users and the calories burnt and prediction is made and accuracy is achieved.
Add images and descriptions in more detail.

2024-05-21 16:52 UTC, Kushal997-das requested changes
@Seersha9802 Kindly look into the comment and update accordingly.

2024-05-21 17:41 UTC, Seersha9802 commented
Yes, I'm working on it.

2024-05-21 20:19 UTC, Seersha9802 commented
@Kushal997-das  I have made the changes, Kindly go through it .

2024-05-22 09:53 UTC, Kushal997-das approved these changes

2024-05-22 09:55 UTC, merged