Added auto commenting featue on new issue and pr
Kushal997-das/Project-Guidance pull request #1112
Opened 2024-05-28 19:27 UTC by suhanipaliwal

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

I have added auto-comment-pr-raise.yml in the .github/workflows directory which will add the feature to auto comment on pull request being raised.

Fixes #1075 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

2024-05-31 04:16 UTC, Kushal997-das requested changes
@suhanipaliwal It's seems you have copy the code from somewhere, kindly do the stuff according to my repo.

2024-05-31 04:16 UTC, Kushal997-das commented on .github/workflows/auto-comment-pr-raise.yml
> +        }
It seems you did copy-paste from somewhere, we sadly do not have any discord but you did added.

2024-05-31 19:48 UTC, suhanipaliwal commented
I'm really sorry for this mistake. I've done the necessary changes now.

2024-06-01 05:28 UTC, Kushal997-das approved these changes
@suhanipaliwal If it's work then only i'll put the level after merge.

2024-06-01 05:29 UTC, merged

2024-07-26 05:27 UTC, suhanipaliwal commented
Please add the label of level1 on this pull request.

2024-08-02 05:59 UTC, suhanipaliwal commented
Could you please add the label of level1