Added DLSR using AutoEncoders
Kushal997-das/Project-Guidance pull request #1113
Opened 2024-05-29 02:25 UTC by Soubeer

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

In this project, I developed a deep learning model using autoencoders to enhance the resolution of low-resolution or damaged images. By training the autoencoder on a dataset of paired high-resolution and low-resolution images, the model learns to reconstruct high-quality images from degraded inputs. This technique leverages the power of neural networks to perform image super-resolution, effectively restoring and improving image quality, making it applicable for various uses such as photo restoration and enhancing visual content in low-bandwidth environments.

Fixes #1016 

### Checklist

- [✓ ] I've read the contribution guidelines.
- [ ✓] I've checked the issue list before deciding what to submit.
- [ ✓] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Nothing similar

2024-05-31 04:48 UTC, Soubeer commented
@Kushal997-das Sir I am sorry , I was really unable to find my Previous PR and thought I didn't make one. I am new to these so I am still finding my way around the block.
If possible can you check one PR and close the other which I opened by mistake?
It would be really helpful.

Thank You

2024-05-31 04:57 UTC, Soubeer commented
> @Soubeer Hello I found you want to add the same project in another repo which is against the rule so I'm closing the PR.
> 
> [here](https://github.com/Kushal997-das/Project-Guidance/pull/1113)

@Kushal997-das Sir the link which you attached for the duplicate repo is this same repo and the same PR page.. It does not open any other repo and as far as I can find, I only made one PR for this repo and one task on this topic for this PR.

2024-05-31 05:32 UTC, Kushal997-das commented
By mistake, I pasted a different link, But it was there, you also said sorry, and now you deleted your comment, that seems how you are. See below attached image and your reply.

![spam](https://github.com/Kushal997-das/Project-Guidance/assets/61356005/fc982be1-dcfb-4f2e-9000-f53cea60f05e)

2024-05-31 05:36 UTC, Soubeer commented
> By mistake, I pasted a different link, But it was there, you also said sorry, and now you deleted your comment, that seems how you are. See below attached image and your reply.
> 
> ![spam](https://private-user-images.githubusercontent.com/61356005/335455469-fc982be1-dcfb-4f2e-9000-f53cea60f05e.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzM5ODUsIm5iZiI6MTcxNzEzMzY4NSwicGF0aCI6Ii82MTM1NjAwNS8zMzU0NTU0NjktZmM5ODJiZTEtZGNmYi00ZjJlLTkwMDAtZjUzY2VhNjBmMDVlLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA1MzQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZTU2MmU0N2U0YzM3NDAwNjcyMDJmYjIxNDcxMGU1OWNhYWE4YTJhMTA2NGEyMGIyNWMwNWIxNDkzZDdlZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vbld_s6MceuL-QGaa_3fyp-wHo0UGOLjgUYx64SJbu8)

@Kushal997-das Yes I did deleted the comment because I would definitely trust you when you say that I made a duplicate repo.So I apologized before even checking.
Then when I went to check there was nothing.
You can check the logs or something from github and show me where the duplicate repo is.

I would not go this far cheating for 10 points. Its not worth it

2024-05-31 05:38 UTC, Kushal997-das commented
I have seen it clearly, by mistake I put another link. I'll not accept your PR.

2024-05-31 05:44 UTC, Soubeer commented
its okay you might not accept. But why are you accusing me of cheating here for "10 points" ? And now you cannot provide me the proof? 
This is not how things work in github ig? There is always a log of changes somewhere. 
I dont want to be rude but this is not acceptable from my side as well. I have checked other PRs also and they have been given the proof of duplicate task. 
I will accept my fault if you can give me mine.

I had 10 repo yesterday and I have the same right now too. I have mailed all my work to the GSSOC team yesterday regarding leaderboard so they have the proof of my work. I dont know how this all adds up to " that seems how you are".

2024-05-31 11:24 UTC, Kushal997-das commented
Okey, I'll open it again make sure there shouldn't be any duplicate I don't
have much time to check thoroughly.

On Fri, 31 May, 2024, 11:14 am Soubeer Koley, ***@***.***>
wrote:

> its okay you might not accept. But why are you accusing me of cheating
> here for "10 points" ? And now you cannot provide me the proof?
> This is not how things work in github ig? There is always a log of changes
> somewhere.
> I dont want to be rude but this is not acceptable from my side as well. I
> have checked other PRs also and they have been given the proof of duplicate
> task.
> I will accept my fault if you can give me mine.
>
> I had 10 repo yesterday and I have the same right now too. I have mailed
> all my work to the GSSOC team yesterday regarding leaderboard so they have
> the proof of my work. I dont know how this all adds up to " that seems how
> you are".
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Kushal997-das/Project-Guidance/pull/1113#issuecomment-2141271706>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOUDPZKV7KRC7JHIHVXCMELZFAE3LAVCNFSM6AAAAABIOAJS46VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNBRGI3TCNZQGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-05-31 14:12 UTC, Soubeer commented
Thank you Sir, I have checked again now , there are no duplicate repos having the same task.
Kindly open this PR again and assign me the label if the task is complete.

2024-06-01 14:03 UTC, Soubeer commented
@Kushal997-das can you open this and merge my file if its okay and provide me with a level?

2024-06-01 16:47 UTC, Kushal997-das commented
@Soubeer Will check .

2024-06-03 15:03 UTC, Kushal997-das requested changes
@Soubeer, the following things need attention:

Add the project under the "basic" section.
Your .ipynb file is not opening.
Update the readme.md file.
Provide detailed instructions in the readme.md file.
Change the project name from Deep_Learning to a more logical name.

2024-06-03 15:03 UTC, Kushal997-das commented on Machine Learning and Data Science/Intermediate/Deep_Learning_Super_Resolution/READme.md
> +* Open a pull request: Submit your changes for review and integration into the main project.
Update the details according to project-guidance. In the readme.md file, include only information related to the project. There is no need to add extra information such as contributions and other details

2024-06-04 01:41 UTC, Soubeer commented
@Kushal997-das changes made

2024-06-07 07:23 UTC, Kushal997-das requested changes
@Soubeer Hi, I'm not feeling well, so I'm taking some time to rest.

Could you please give the project a more logical name? 'Deep_learning' doesn't seem suitable. Try to come up with a name that better fits the nature of the project.

Also, make sure you fetch the updated version of the project.

2024-06-07 07:50 UTC, Soubeer commented
@Kushal997-das Changed the name to Super_Resolution_Using_Deep_Learning

2024-06-08 17:33 UTC, Kushal997-das requested changes
@Soubeer As mentioned in last comment fetch the repo once again.

2024-06-08 17:52 UTC, Soubeer commented
@Kushal997-das updated all the necessities.

2024-06-10 14:43 UTC, Kushal997-das requested changes
Hi @Soubeer, I can't keep telling you the same thing again and again. Yet, you still don't do things properly. [Here](https://github.com/Soubeer/Project-Guidance/blob/main/Machine%20Learning%20and%20Data%20Science/README.md#level-1-basic-), you haven't updated the project name.

2024-06-10 14:55 UTC, Soubeer commented
> Hi @Soubeer, I can't keep telling you the same thing again and again. Yet, you still don't do things properly. [Here](https://github.com/Soubeer/Project-Guidance/blob/main/Machine%20Learning%20and%20Data%20Science/README.md#level-1-basic-), you haven't updated the project name.

mb Sir, updated and provided the link for the readme in basic with the main branch from ur repo...should activate the link once its approved...kindly check if there are any more problems.

2024-06-10 16:36 UTC, Kushal997-das requested changes
After 25 , 26 should be in right hand side. And this is the last time I'm saying if this time everything not correct I'll close the PR.

![here 26](https://github.com/Kushal997-das/Project-Guidance/assets/61356005/ebd4637e-07be-4032-910d-2d009b6f03f9)

2024-06-13 16:50 UTC, Kushal997-das approved these changes
@Soubeer 👍🏻

2024-06-13 16:51 UTC, merged