IoT Based Automated Billing System
Kushal997-das/Project-Guidance pull request #1136
Opened 2024-05-30 18:05 UTC by Vrisha213

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes

### Description

Add the code, video readme and image files for the project

Fixes #1077 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2024-05-31 04:37 UTC, Kushal997-das requested changes
@Vrisha213 Hello add your project [here](https://github.com/Vrisha213/Project-Guidance/blob/main/IOT(Internet%20of%20Things)/README.md)

2024-05-31 04:37 UTC, Kushal997-das commented on IOT(Internet of Things)/Basic/ESP32_Billing_System/readme.md
> +
I want image should display here instead of any link .

2024-05-31 13:31 UTC, Vrisha213 commented
@Kushal997-das Hi, I've made the required changes. Please check.
Thank you

2024-05-31 13:38 UTC, Kushal997-das commented
@Vrisha213 Do you have LinkedIn?

2024-05-31 15:57 UTC, Vrisha213 commented
Done @Kushal997-das

2024-06-01 03:28 UTC, Kushal997-das requested changes
@Vrisha213 Reduce the size of image a bit.

2024-06-01 03:28 UTC, Kushal997-das commented on IOT(Internet of Things)/README.md
> +| 22. | [Arduino_Line_Follower_Robot](https://github.com/deedGhost/Project-Guidance/tree/main/IOT(Internet%20of%20Things)/Basic/Arduino_Line_Follower_Robot)| 23. | [ESP32_Billing_System](https://gith
Change the project name `ESP32_Billing_System` to `Automated Billing System`

2024-06-01 17:16 UTC, Vrisha213 commented
Done @Kushal997-das .

2024-06-02 15:33 UTC, Kushal997-das approved these changes

2024-06-02 15:34 UTC, merged