RFID Door Lock System with Arduino
Kushal997-das/Project-Guidance pull request #1499
Opened 2024-10-17 08:06 UTC by IkkiOcean

### 📝 Description 

This pull request adds an **RFID Door Lock System** implemented using **Arduino**. The system uses an RFID module to read RFID tags and allows access to authorized users by unlocking the door using a servo motor. It also includes an LCD display to show the current status of the system (e.g., access granted or denied).

The project is structured into two main parts:
- **main.ino**: The primary script that manages the RFID authentication and door lock mechanism.
- **scan.ino**: A helper script for scanning RFID tags and obtaining their unique identifiers (UIDs), which can be added to the list of authorized users.

Components
- **Arduino UNO** x 1
- **RFID Module (MFRC522)** x 1
- **LCD Display (16x2)** x 1
- **I2C Module for LCD** x 1
- **Servo Motor (SG90)** x 1
- **Door Lock Mechanism** x 1

This feature will enhance security and provide a hands-free access mechanism.

### ISSUE

- Closes : #1440 

### 🏷️ Initiative Participation *(Required)*

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [x] 🌼 GSSoC 2024 Extd.
- [x] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

2024-10-18 15:05 UTC, IkkiOcean commented
@Kushal997-das sir please review and merge soon

2024-10-23 13:58 UTC, Kushal997-das requested changes
@IkkiOcean Update [readme.md](https://github.com/IkkiOcean/Project-Guidance/blob/rfid-project/IOT(Internet%20of%20Things)/README.md) file.

2024-10-23 20:20 UTC, IkkiOcean commented
@Kushal997-das done! did the requested changes.

2024-10-24 04:26 UTC, Kushal997-das approved these changes

2024-10-24 04:27 UTC, merged