Addition of Maze Solver Application
Kushal997-das/Project-Guidance pull request #1583
Opened 2024-10-29 19:04 UTC by Mahak-Agrawal-304

# Project-Guidance! 🎊🎈

### Welcome! 🎉

Thank you for visiting our repository! We're excited to have you here. If you find this project useful, please consider giving it a star! ⭐

### 🎉 Have you reviewed the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)? 🤔 *(Required)*

- [X] YES
- [ ] NO

### 📝 Description 
This application provides an interactive way to visualize and solve a maze using a depth-first search (DFS) algorithm. Users can load a maze from a .txt file, solve it, and view the solution and explored states visually.
I have used tkinter for implementing its interactive GUI. Here, the user can load an image in the form of .txt file, as shown in example:
![Screenshot (3094)](https://github.com/user-attachments/assets/d5c2b5e1-0b01-4f3d-b8a4-4b0ea2855979)

The program loads this image and saves it in the device in the form of a png file under the name 'temp_maze.png'
![Screenshot (3097)](https://github.com/user-attachments/assets/9482f976-9775-4c4c-925a-7ada65a62185)

After clicking solve button, the program begins to solve the maze and presents its solution on the interface. It also saves it as 'solved_maze.png' on the device
![Screenshot (3098)](https://github.com/user-attachments/assets/d83bdccd-b4f8-4a7e-a252-b2816c806f03)

 

### 🔧 Fixes #1539 

### 🏷️ Initiative Participation *(Required)*

This pull request is associated with the following initiative. Please choose the one you are contributing to:

- [ ] 🌸 GSSoC (Girl Script Summer of Code)
- [X] 🌼 GSSoC 2024 Extd.
- [ ] 🍂 Hacktoberfest 2024
- [ ] ❄️ Script Winter of Code (SWoC)
- [ ] ⛄ Winter of Blockchain (WoB)
- [ ] 🙋‍♂️ Personal
- [ ] 📌 Other (please specify): _______________

2024-10-30 05:54 UTC, Kushal997-das requested changes
Update your project [here](https://github.com/Kushal997-das/Project-Guidance/blob/main/Desktop%20Application/README.md)

2024-10-30 12:52 UTC, Mahak-Agrawal-304 commented
Alright @Kushal997-das

2024-11-04 11:14 UTC, Mahak-Agrawal-304 commented
Done @Kushal997-das

2024-11-04 14:58 UTC, Kushal997-das approved these changes

2024-11-04 14:59 UTC, merged