Added Weather App Project
Kushal997-das/Project-Guidance pull request #240
Opened 2022-03-02 14:41 UTC by AdmiralAnne

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

- [x]  YES

### Description

Added a new project called "weather app" to BasicWebDevelopment - It runs on the browser and doesn't need any frameworks. Runs using simple html, css and JavaScript.

Fixes #204 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

none

2022-03-03 16:30 UTC, Kushal997-das requested changes
Please fix this bug @AdmiralAnne

2022-03-03 16:30 UTC, Kushal997-das commented on Web Development/Basic/Weather App/README.md
> +![alt text for screen readers](Icons\screenshot.png "Text to show on mouseover")
This link is not working please fix this @AdmiralAnne

2022-03-03 16:56 UTC, prakhar3062 commented on Web Development/Basic/Weather App/README.md
> +![alt text for screen readers](Icons\screenshot.png "Text to show on mouseover")
Link is working but may be there is issue in image 
![Screenshot (626)](https://user-images.githubusercontent.com/82047120/156612948-d96cf783-b674-444b-b073-b8d69372aaed.png)

2022-03-03 17:51 UTC, prakhar3062 approved these changes
@photon149 okay from my side

2022-03-04 10:36 UTC, photon149 approved these changes
Looks good to me 
@Kushal997-das please review and merge the same

2022-03-04 11:01 UTC, Kushal997-das approved these changes
@AdmiralAnne Good 👍

2022-03-04 11:03 UTC, merged