casio added to webdev
Kushal997-das/Project-Guidance pull request #253
Opened 2022-03-03 05:54 UTC by HarshitShukla01

### Description

Added Casio to web development

issue #208 resolved

2022-03-03 17:32 UTC, prakhar3062 commented
@HarshitShukla01  add readme file for your project

2022-03-04 03:46 UTC, Kushal997-das requested changes
@HarshitShukla01 Add something about your project in `readme.md` file like @prakhar3062 said and yeah your project should under basic . Like this as below i mentioned 
webDevelopment/basic/casio.

2022-03-04 04:28 UTC, HarshitShukla01 commented
I am done the changes now pls review it.

2022-03-04 04:30 UTC, HarshitShukla01 commented
> [<img alt="@Kushal997-das" width="20" height="20" src="https://avatars.githubusercontent.com/u/61356005?s=60&amp;u=3e4cad94795872d019c84f31cfe724f9774c2ba7&amp;v=4">](/Kushal997-das) [Kushal997-das](/Kushal997-das) added the [ Pending ](/Kushal997-das/Project-Guidance/labels/Pending) label [43 minutes ago](#event-6182599398)

I am done the changes now pls review it.

2022-03-04 04:40 UTC, Kushal997-das approved these changes
LGTM 👍 

@prakhar3062 Please check

2022-03-04 08:09 UTC, prakhar3062 commented on Web Development/Basic/Casio/README.md
> +![Cadio](demo.png "This is a sample image.")
Image is not visible. Please write the correct address

2022-03-04 15:02 UTC, HarshitShukla01 commented on Web Development/Basic/Casio/README.md
> +![Cadio](demo.png "This is a sample image.")
![image](https://user-images.githubusercontent.com/75080333/156786986-2087afa4-71df-4e56-863b-0c97f59cee1b.png)

its visible for me

2022-03-04 15:04 UTC, prakhar3062 approved these changes
@photon149 okay from my side

2022-03-04 17:18 UTC, photon149 approved these changes
Looks good to me.
@Kushal997-das please merge the same in case of no conflicts.

2022-03-05 04:04 UTC, merged