Created Calculatro using python GUI
Kushal997-das/Project-Guidance pull request #266
Opened 2022-03-03 14:45 UTC by Vikash-8090-Yadav

Hey , Hop u r doing good !!  :heart: 
I created the calculator using python gui . its a basic calculator which used for the basic airthmrtic operation's .Along with this i 

also make the readme file for the calculator 
Issue no: 
Fixes #188 

@Kushal997-das  plss chek this

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.

2022-03-04 04:44 UTC, Kushal997-das commented on Web Development/Basic/Calculator_GUI/Readme.md
> +![Screenshot from 2022-03-03 19-57-32](https://user-images.githubusercontent.com/85225156/156588187-bb8f1184-11cd-4d60-a388-573fc7a0b61c.png)
Please reduce the size of image !!

2022-03-04 04:45 UTC, Kushal997-das commented on Web Development/Basic/Calculator_GUI/Readme.md
> +![Screenshot from 2022-03-03 19-57-40](https://user-images.githubusercontent.com/85225156/156587954-828b1ba9-99af-42fa-bee4-0b0cbf0a19d5.png)
Reduce the size of the image !

2022-03-04 04:46 UTC, Kushal997-das requested changes
@Vikash-8090-Yadav Please reduce the image size which ever exits in your `readme.md` file

2022-03-04 11:19 UTC, Kushal997-das approved these changes
@Vikash-8090-Yadav Great 👍 
LGTM 👍 

Please check @photon149

2022-03-04 12:04 UTC, photon149 commented on Web Development/Basic/Calculator_GUI/Calculator_GUI.py
> +root.title("GROUP- 7 PROJECT - CALCULATOR CU (LAB MST ) A.I == PYTHON GUI")
@Vikash-8090-Yadav Please Update the title of the project.

2022-03-04 12:05 UTC, photon149 requested changes
Please do the requested changes

2022-03-04 17:21 UTC, photon149 approved these changes
looks good to me.
@prakhar3062 please have a look.

2022-03-05 04:10 UTC, Kushal997-das commented
@prakhar3062 Please have a look !!

2022-03-05 06:52 UTC, prakhar3062 approved these changes
@Kushal997-das  everything is fine

2022-03-06 15:57 UTC, Kushal997-das requested changes
@Vikash-8090-Yadav Do one changes this project uses only Tkinter in python . So this should go under **Desktop application** [Under this ](https://github.com/Kushal997-das/Project-Guidance/tree/main/Desktop%20Application/Basic/Python)

2022-03-06 19:04 UTC, Kushal997-das requested changes
Your dasktop image is visible so crop the image only calculator should shown in the readme file.

2022-03-07 04:35 UTC, Kushal997-das approved these changes
LGTM 💯

2022-03-07 04:36 UTC, merged