Gas Leakage Detection Software
Kushal997-das/Project-Guidance pull request #269
Opened 2022-03-03 16:19 UTC by advaita-saha

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes

### Description

Detection of gas leakage or smoke, and also notifying the user at the moment of detection, using a system pop up warning

Fixes #250 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2022-03-03 19:27 UTC, advaita-saha commented
I have created the software, please review my PR and merge it. @Kushal997-das

2022-03-04 04:51 UTC, Kushal997-das commented on IOT(Internet of Things)/Intermediate/README.md
> +[Gas Leakage Detection System](https://github.com/advaita-saha/Project-Guidance/tree/main/IOT(Internet%20of%20Things)/Intermediate/gas%20leakage%20detection)
Please add details here instead of just link and put gif or photo of your project into this file .

2022-03-04 04:52 UTC, Kushal997-das commented on IOT(Internet of Things)/Intermediate/gas leakage detection/LICENSE
> +                    GNU GENERAL PUBLIC LICENSE
Delete this file `License`

2022-03-04 04:53 UTC, Kushal997-das commented on IOT(Internet of Things)/README.md
> -
Delete this file .

2022-03-04 04:54 UTC, Kushal997-das requested changes
@advaita-saha There are lot of things you have to change i already mentioned please change accordingly .

2022-03-04 05:11 UTC, advaita-saha commented on IOT(Internet of Things)/Intermediate/README.md
> +[Gas Leakage Detection System](https://github.com/advaita-saha/Project-Guidance/tree/main/IOT(Internet%20of%20Things)/Intermediate/gas%20leakage%20detection)
Details of the project is provided in the README within the project directory
Do I need to write the same again in this README file inside the Intermediate directory??

2022-03-05 04:17 UTC, Kushal997-das commented on IOT(Internet of Things)/Intermediate/README.md
> +[Gas Leakage Detection System](https://github.com/advaita-saha/Project-Guidance/tree/main/IOT(Internet%20of%20Things)/Intermediate/gas%20leakage%20detection)
@advaita-saha Delete this readme.md file from here no need to add here .

2022-03-05 06:30 UTC, advaita-saha commented
I have completed all the requested changes as asked, please review and merge the PR @Kushal997-das

2022-03-06 16:00 UTC, Kushal997-das requested changes
@advaita-saha Change the folder location , your project should go under [this](https://github.com/Kushal997-das/Project-Guidance/tree/main/IOT(Internet%20of%20Things)/Intermediate)

2022-03-06 16:12 UTC, advaita-saha commented
> @advaita-saha Change the folder location , your project should go under [this](https://github.com/Kushal997-das/Project-Guidance/tree/main/IOT(Internet%20of%20Things)/Intermediate)

Yess I my project folder is under Intermediate folder only, please check once

2022-03-07 04:49 UTC, Kushal997-das approved these changes

2022-03-07 04:50 UTC, Kushal997-das commented
@photon149 Check !

2022-03-07 05:10 UTC, photon149 requested changes
@advaita-saha A few modifications.
-There is no need to add an empty readme file in the Intermediate folder and IOT folder , please remove the same.

2022-03-07 05:10 UTC, photon149 commented on IOT(Internet of Things)/Intermediate/gas leakage detection/alarm_run.py
> +#created by Advaita Saha on 5/3/2020 7:49PM IST
Delete this as it shows it past dated.

2022-03-07 05:10 UTC, photon149 commented on IOT(Internet of Things)/Intermediate/gas leakage detection/alarm_run.py
> +
Add comments

2022-03-07 06:09 UTC, advaita-saha commented
I have added the comments and removed the lines requested @Kushal997-das @photon149

2022-03-07 06:15 UTC, photon149 approved these changes
looks fine to me.
@prakhar3062 have a look.

2022-03-07 14:17 UTC, merged