Starbucks Frontend Clone
Kushal997-das/Project-Guidance pull request #271
Opened 2022-03-03 16:57 UTC by dexterousb

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

### Description

(Write your answer here.)

Fixes #232

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2022-03-04 04:56 UTC, Kushal997-das commented on Web Development/Intermediate/Starbucks Frontend Clone/readme.md
> +# Starbucks Homepage Clone
@dexterousb Add gif about your project in this file .

2022-03-04 04:56 UTC, Kushal997-das requested changes
@dexterousb

2022-03-07 15:16 UTC, dexterousb commented on Web Development/Intermediate/Starbucks Frontend Clone/readme.md
> +# Starbucks Homepage Clone
[https://imgur.com/hc1CtTPhttps://imgur.com/hc1CtTP](url)
link to gif file plus added another gif image in project

2022-03-07 15:18 UTC, dexterousb commented
I have thereby added the gif of the project , kindly merge the pull request.

2022-03-08 02:19 UTC, Kushal997-das commented
@dexterousb Add gif in readme.md file not just link .

2022-03-09 03:56 UTC, dexterousb commented
Hi I have added the gif image to the readme file. Kindl merge the pull request! Thanks

2022-03-09 17:16 UTC, Kushal997-das commented
@dexterousb Please send a new Pull request !

2022-03-09 17:17 UTC, closed without merging