Tic-Tac-Toe game using java
Kushal997-das/Project-Guidance pull request #295
Opened 2022-03-04 15:09 UTC by nitishkumar07

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ? YES

(Write your answer here.)

### Description
Added Tic-Tac-Toe game 
(Write your answer here.)

Fixes #issue_no
#289 

### Checklist

- [ X ] I've read the contribution guidelines.
- [ X ] I've checked the issue list before deciding what to submit.
- [ X ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2022-03-04 17:33 UTC, photon149 commented
@nitishkumar07 please follow PR guidelines.
- Update the issue number correctly in the PR , write the issue number in place of "#issue_no"
- Add further Details in your README , it's too short.

2022-03-05 03:06 UTC, nitishkumar07 commented
I have updated readme file 
is it ok?

2022-03-06 05:15 UTC, photon149 approved these changes
Looks good to me.
@prakhar3062 over to you.

2022-03-06 06:45 UTC, prakhar3062 approved these changes
Everything works fine

2022-03-06 16:42 UTC, Kushal997-das commented on Desktop Application/Basic/Java/TicTacToe/.classpath
> +<?xml version="1.0" encoding="UTF-8"?>
Delete this file if not required !

2022-03-06 16:43 UTC, Kushal997-das commented on Desktop Application/Basic/Java/TicTacToe/.project
> +<?xml version="1.0" encoding="UTF-8"?>
@nitishkumar07 Delete this file if not required !!

2022-03-06 16:44 UTC, Kushal997-das requested changes
@nitishkumar07 Delete all (.) file if not required .

2022-03-07 01:00 UTC, nitishkumar07 commented
I have removed hidden files .
Please review it.

2022-03-07 04:52 UTC, Kushal997-das approved these changes

2022-03-07 04:53 UTC, merged