added algorithm visualiser app
Kushal997-das/Project-Guidance pull request #296
Opened 2022-03-04 15:41 UTC by Phoenix-031

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

Added sorting algorithm visualiser app with consisting of various sorting algorithms

Fixes #244

### Checklist

- [ ✅] I've read the contribution guidelines.
- [ ✅] I've checked the issue list before deciding what to submit.
- [ ✅] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

None

2022-03-04 17:37 UTC, photon149 approved these changes
@Phoenix-031 Interactive Visuals 👍🏻 
@prakhar3062 please have a look , approved from my end.

2022-03-06 06:51 UTC, prakhar3062 reviewed
@Phoenix-031 nice work . okay from my side

2022-03-06 10:04 UTC, Phoenix-031 commented
@prakhar3062 thankyou for your approval do i have to do anything else or will it get merged in due time?

2022-03-06 17:05 UTC, Kushal997-das requested changes
@Phoenix-031 Good project , One thing when i ran this project it shows only `bubble sort` and screen got  freezed. Can You mention in your `readme.md` file that how user can use or play with the output . 
And reduce the image size whose are in `readme.md` file .

2022-03-06 17:57 UTC, Phoenix-031 commented
Sure I am adding the process of using this to the readme file and i will be resizing the gifs as much as possible.
It shows bubble sort first bcuz that is set to be the default algo u can change that by pressing M or S or I or Q etc as mentioned at the top of the screen .
I also ran the program again i couldn't find anything that would freeze the program.

2022-03-07 04:57 UTC, Kushal997-das commented on Desktop Application/Intermediate/Python/Algorithm_visualiser/README.md
> +![alt-text](./Images/AlgorithmVisualiser.png)
This link is not working !

2022-03-07 04:57 UTC, Kushal997-das requested changes
Change !!

2022-03-07 05:16 UTC, Phoenix-031 commented
added the image now it'll be visible :)

2022-03-07 05:28 UTC, Kushal997-das approved these changes
@Phoenix-031 💯

2022-03-07 05:29 UTC, merged