Updated UI of Contact Form
Kushal997-das/Project-Guidance pull request #297
Opened 2022-03-04 16:01 UTC by shania-balkhi

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes, I have read it thoroughly.

### Description

• added 'glassmorphism' web design to the form.
• applied vanilla-tilt effect to the form to make the form visually attractive and playful.
• added the favicon of GSSoC so that the page appears authentic, original and complete. 
• the site now seems visually attractive and user friendly!

Fixes #247 

### Checklist
- [✓ ] I've read the contribution guidelines.
- [ ✓] I've checked the issue list before deciding what to submit.
- [✓ ] I've edited the `README.md` and link to my code.

2022-03-07 05:02 UTC, Kushal997-das commented on Web Development/Basic/Contact Form/README.md
> +## [Try Now](https://shania-balkhi.github.io/Project-Guidance/)☺
Delete this !!

2022-03-07 05:06 UTC, Kushal997-das commented on _config.yml
> +theme: jekyll-theme-cayman
Delete this one !

2022-03-07 05:07 UTC, Kushal997-das commented on Web Development/Basic/Contact Form/README.md
Don't leave white space here !

2022-03-07 05:10 UTC, Kushal997-das requested changes
@shania-balkhi Changes all the things which i mentioned and delete this (Web Development/Basic/Contact Form/favicon.png)file.

2022-03-08 15:30 UTC, Kushal997-das commented
@shania-balkhi OMG You added duplicated `webdevelopment` folder please delete this

2022-03-08 15:31 UTC, shania-balkhi commented on _config.yml
> +theme: jekyll-theme-cayman
Done Sir!

2022-03-08 15:31 UTC, shania-balkhi commented on Web Development/Basic/Contact Form/README.md
Done Sir!

2022-03-08 15:32 UTC, shania-balkhi commented
> @shania-balkhi OMG You added duplicated `webdevelopment` folder please delete this

Okay sir!

2022-03-12 04:15 UTC, Kushal997-das commented
@shania-balkhi ?

2022-03-13 11:31 UTC, Kushal997-das commented
@shania-balkhi Are you going to do the changes ? Or else your PR will close .

2022-03-15 03:23 UTC, shania-balkhi commented
> @shania-balkhi Are you going to do the changes ? Or else your PR will close .

@Kushal997-das I'm on it. By the end of this week it'll be done. (had gotten stuck because of the re-opening of my college). Kindly wait till I work on the task!

2022-03-17 17:44 UTC, closed without merging