Add card check
Kushal997-das/Project-Guidance pull request #300
Opened 2022-03-04 18:49 UTC by Satyam26-09

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

### Description

The project is used to check the authenticity of the credit card. This program follows Luhn’s Algorithm (which the most card follows). In this stage the program works on fewer number of cards...hope for collaborative work to expand it.

Fixes #294 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2022-03-05 00:59 UTC, photon149 reviewed
@Satyam26-09 Please Add Output SS in your README file as well.

2022-03-05 04:14 UTC, Satyam26-09 commented
@photon149 Done....

2022-03-06 05:16 UTC, photon149 approved these changes
Looks good to me.
@prakhar3062 please have a look.

2022-03-06 06:42 UTC, prakhar3062 approved these changes
Everything works fine

2022-03-06 16:49 UTC, Kushal997-das commented on Desktop Application/Basic/C++/Credit Card Checker/ccc.cpp
> +
Delete this space !

2022-03-06 16:49 UTC, Kushal997-das commented on Desktop Application/Basic/C++/Credit Card Checker/ccc.cpp
> +
Delete this space !

2022-03-06 16:49 UTC, Kushal997-das commented on Desktop Application/Basic/C++/Credit Card Checker/Documents/README.md
> +This project is used to check the authenticity of the credit card. This program follows Luhn’s Algorithm (which the most card follows). In this stage the program works on fewer number of cards which
Change this file location .

2022-03-06 16:51 UTC, Kushal997-das requested changes
@Satyam26-09 Your `readme.md` file should under[this](https://github.com/Satyam26-09/Project-Guidance/tree/Add_CardCheck/Desktop%20Application/Basic/C%2B%2B/Credit%20Card%20Checker) Instead [this](https://github.com/Satyam26-09/Project-Guidance/blob/Add_CardCheck/Desktop%20Application/Basic/C%2B%2B/Credit%20Card%20Checker/Documents/README.md) .

2022-03-06 18:20 UTC, Satyam26-09 commented on Desktop Application/Basic/C++/Credit Card Checker/ccc.cpp
> +
done

2022-03-06 18:20 UTC, Satyam26-09 commented on Desktop Application/Basic/C++/Credit Card Checker/ccc.cpp
> +
done..

2022-03-06 18:22 UTC, Satyam26-09 commented on Desktop Application/Basic/C++/Credit Card Checker/Documents/README.md
> +This project is used to check the authenticity of the credit card. This program follows Luhn’s Algorithm (which the most card follows). In this stage the program works on fewer number of cards which
done..

2022-03-06 18:24 UTC, Satyam26-09 commented on Desktop Application/Basic/C++/Credit Card Checker/Documents/README.md
> +This project is used to check the authenticity of the credit card. This program follows Luhn’s Algorithm (which the most card follows). In this stage the program works on fewer number of cards which
@Kushal997-das I have changed the file location simply by deleting and creating new file....is there any other way to do so...kindly share

2022-03-06 18:32 UTC, Satyam26-09 commented on Desktop Application/Basic/C++/Credit Card Checker/ccc.cpp
> +
@Kushal997-das I have used github to made changes in ccc.cpp as I was facing problem to do so with git bash...
![Screenshot](https://user-images.githubusercontent.com/96687053/156936898-079c3c06-be65-41e6-8141-8448be281c51.png) showing this problem..
kindly help...

2022-03-06 19:22 UTC, Kushal997-das approved these changes
@Satyam26-09 :+1:

2022-03-06 19:22 UTC, merged