Image Request Feature added
Kushal997-das/Project-Guidance pull request #301
Opened 2022-03-04 19:01 UTC by AlapanDas

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #issue_no

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2022-03-05 01:04 UTC, photon149 commented
@AlapanDas Please Read Contributing Guidelines while making the PR. Also , a few pointers which need to be addressed  :-
- Mention the Issue Number to which the particular PR relates.
- Enhance Code Readability (Add Comments)
- Add a README file and give a brief description of your project (including Output SS)

2022-03-05 14:18 UTC, AlapanDas commented
@photon149 please check the PR once more i have successfully processed the changes

2022-03-06 05:22 UTC, photon149 requested changes
@AlapanDas You need to create a new file in your directory called as  "README.md" in your subdirectory and add the description and SS there.

2022-03-06 09:58 UTC, AlapanDas commented
Done !.

2022-03-06 10:04 UTC, photon149 commented
Just one Minor change , you don't require to Add the Issue number on your README file.
Just delete the part and it's good to go.
@prakhar3062 looks fine from my end , have a look

2022-03-06 10:07 UTC, AlapanDas commented
okay brother , just a minute
Done!

2022-03-06 15:50 UTC, prakhar3062 approved these changes
okay from side

2022-03-06 15:56 UTC, AlapanDas commented
Please add a gssoc level

2022-03-06 16:10 UTC, Kushal997-das requested changes
@AlapanDas Change the location of the folder your project should go under 
[Basic level](https://github.com/AlapanDas/Project-Guidance/tree/main/Desktop%20Application/Basic/Python).
And reduce the image size please make these changes ASAP.

2022-03-06 16:38 UTC, AlapanDas commented
I am changing the folder, but bro the image size is dynamic , since the user can select 4k or 2k picture the file size will increase dynamically with user's input . The best i can do is upload a blank container.jpg file but if the user asks for a 4k file it will take 1-3mb and we cannot control it .

2022-03-06 17:13 UTC, Kushal997-das commented on Desktop Application/Intermediate/Python/Image Request/Readme.md
> +![image](https://user-images.githubusercontent.com/71692310/156886857-4f6c1111-4473-4303-8242-7037ec69e111.png)
Here you can reduce the image file . Give height or weight to image and you can easily reduce the size of the image .

2022-03-06 17:13 UTC, Kushal997-das commented on Desktop Application/Intermediate/Python/Image Request/Readme.md
> +![image](https://user-images.githubusercontent.com/71692310/156886858-32cadc78-7a50-4db0-82fb-94df38e7195d.png)
Reduce image size

2022-03-06 17:14 UTC, Kushal997-das reviewed
Reduce the image size.

2022-03-06 17:15 UTC, Kushal997-das commented
> I am changing the folder, but bro the image size is dynamic , since the user can select 4k or 2k picture the file size will increase dynamically with user's input . The best i can do is upload a blank container.jpg file but if the user asks for a 4k file it will take 1-3mb and we cannot control it .

You can easily do man in your readme.md file doesn't matter it is in random/dynamic or not .

2022-03-06 18:31 UTC, AlapanDas commented
accha in readme file okay okay i was thinking of the original file

2022-03-06 18:40 UTC, AlapanDas commented
Done

2022-03-06 19:14 UTC, Kushal997-das approved these changes

2022-03-06 19:17 UTC, merged