Snake_Game #299
Kushal997-das/Project-Guidance pull request #331
Opened 2022-03-06 18:36 UTC by AnonymousCodes911

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

Snake Game using Pygame with Keyboard Interrupts 

Fixes #299

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

NA

2022-03-09 18:04 UTC, AnonymousCodes911 commented
@photon149 Noted, will do the needful soon. Thankyou

2022-03-13 11:32 UTC, Kushal997-das commented
@AnonymousCodes911 Are you going to do the changes ? Or else your PR will close .

2022-03-13 12:58 UTC, AnonymousCodes911 commented
@Kushal997-das , sorry for the inconvenience it will be done today!

2022-03-14 03:56 UTC, Kushal997-das commented on Desktop Application/Basic/Python/Snake_Game/Readme.md
> +<p align="center"><img src="https://github.com/Anonymouscodes911/Project-Guidance/blob/main/Desktop%20Application/Basic/Python/Snake_Game/?Snake_Game_gif.gifraw=true" ></p>
This link is not working !

2022-03-14 03:58 UTC, Kushal997-das commented on Desktop Application/Basic/Python/Snake_Game/Readme.md
> +### <p align="center">***_Show Love by Starring this Repo_***</p>
Your `readme.md` file have lot's of `#` and `*` you might do something else with that may be you want to `bold the text so for this you have to check the space .

2022-03-14 03:59 UTC, Kushal997-das commented on Desktop Application/Basic/Python/Snake_Game/Readme.md
> +- ### ***_[Connect With Me on LinkedIn to Get Regular Project Updates](https://www.linkedin.com/in/utkarshkumar911/ "LCO")_***
Delete this also because this line has start with ### it's not look good please do focus as well as documentation part.

2022-03-14 04:00 UTC, Kushal997-das requested changes
@AnonymousCodes911 Add about your project output in `readme.md` section .

2022-03-14 04:23 UTC, AnonymousCodes911 commented on Desktop Application/Basic/Python/Snake_Game/Readme.md
> +- ### ***_[Connect With Me on LinkedIn to Get Regular Project Updates](https://www.linkedin.com/in/utkarshkumar911/ "LCO")_***
Yes sir, will do!

2022-03-14 04:23 UTC, AnonymousCodes911 commented on Desktop Application/Basic/Python/Snake_Game/Readme.md
> +### <p align="center">***_Show Love by Starring this Repo_***</p>
Thank you sir, understood

2022-03-15 06:09 UTC, AnonymousCodes911 commented
closed in #410

2022-03-15 06:10 UTC, closed without merging