python-ping-pong-game
Kushal997-das/Project-Guidance pull request #333
Opened 2022-03-06 20:17 UTC by mayank-del

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

This is nodemailer by which you can mail a form having message to anyone, when i was beginner , i suffered alot to learn to this .So, i am sharing this to open source.

Fixes #330

### Checklist

- [ y] I've read the contribution guidelines.
- [y ] I've checked the issue list before deciding what to submit.
- [ y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

No issues present in this, it works perfectly

2022-03-09 14:44 UTC, photon149 commented
@mayank-del Please check the issue and files changed.They are for ping pong game

2022-03-09 16:04 UTC, mayank-del commented
Very sorry for that, I will fix it today

On Wed, 9 Mar 2022, 20:15 photon149, ***@***.***> wrote:

> @mayank-del <https://github.com/mayank-del> Please check the issue and
> files changed.They are for ping pong game
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Kushal997-das/Project-Guidance/pull/333#issuecomment-1062994737>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATTNVGRFNYYZQ5WMMHIWCSDU7C2PZANCNFSM5QBSAXFA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-09 18:38 UTC, mayank-del commented
@photon149  Please check  it once, I have sent nodemailer now.

2022-03-10 14:46 UTC, photon149 requested changes
@mayank-del Please attach a README file , alongside output ss/

2022-03-10 17:31 UTC, mayank-del commented
sir see I added Screenshots  of output in description at the top and added Readme.md in the recent commit as well

2022-03-11 03:40 UTC, photon149 commented
@mayank-del Add the output SS in your README.md file as well.

2022-03-12 10:07 UTC, mayank-del commented
@photon149 , please check it , I have copied the screenshot to readme.md as well

2022-03-13 08:39 UTC, photon149 commented
Great . Approved from my end.
@Kushal997-das @prakhar3062 have a look.

2022-03-13 09:05 UTC, prakhar3062 approved these changes
okay but you added two project node mailer and pingpong in same pr

2022-03-13 09:16 UTC, mayank-del commented
@prakhar3062 sir, i think nodemailer is at correct position , i have to change directory of pingpong game, can u suggest any different directory

2022-03-13 11:36 UTC, Kushal997-das commented on Web Development/Basic/NodeMailer/README.md
> +![Screenshot 2022-03-10 212659](https://user-images.githubusercontent.com/82238106/158013570-f79d29b5-89f1-4839-bf1a-9f634ac4b296.png)
Reduce the image size .

2022-03-13 11:36 UTC, Kushal997-das commented on Web Development/Basic/NodeMailer/README.md
> +![Screenshot 2022-03-10 212659](https://user-images.githubusercontent.com/82238106/158013570-f79d29b5-89f1-4839-bf1a-9f634ac4b296.png)
Reduce the image size.

2022-03-13 11:36 UTC, Kushal997-das commented on Web Development/Basic/NodeMailer/README.md
> +![Gmail](https://user-images.githubusercontent.com/82238106/158013610-f834af1c-5937-4657-aaa5-c49295321b16.png)
Reduce the image size.

2022-03-13 11:37 UTC, Kushal997-das requested changes
@mayank-del Do the required changes ASAP

2022-03-20 17:48 UTC, mayank-del commented
@Kushal997-das  ,Sir i fixed everything , now please accept the pull request

2022-03-21 05:57 UTC, Kushal997-das reviewed
@mayank-del You didn't change anything so by the end of this day(EOD) change it or else we gonna close this PR .

2022-03-22 04:02 UTC, mayank-del commented
@Kushal997-das  sir you told to to reduce  screenshot size only , i did it,. now, please merge it.

2022-03-22 04:03 UTC, mayank-del commented
@Kushal997-das  , please check , screenshot size reduced

2022-03-22 04:04 UTC, mayank-del commented
@Kushal997-das  sir , kindly check it and inform me, please

2022-03-22 04:23 UTC, Kushal997-das commented on Web Development/Basic/NodeMailer/README.md
> +![Screenshot 2022-03-10 212659](https://user-images.githubusercontent.com/82238106/158013570-f79d29b5-89f1-4839-bf1a-9f634ac4b296.png)
Reduce the image size from here only means from`readme.md` file

2022-03-22 04:24 UTC, Kushal997-das commented
> @Kushal997-das sir , kindly check it and inform me, please

2022-03-22 04:25 UTC, Kushal997-das commented
@mayank-del reduce the image size from`readme.md` file don't you understand ?

2022-03-22 05:38 UTC, mayank-del commented
@Kushal997-das , I changed the size of img in both readme.md  as well as above in comment, please check and merge .

2022-03-22 06:25 UTC, Kushal997-das commented on Web Development/Basic/NodeMailer/README.md
> +![Gmail](https://user-images.githubusercontent.com/82238106/159414755-b1c2909c-9090-4da8-ae0f-5fdc0dbdd5a3.jpg)
Use this format to reduce the size .

`<img align="center" width="300px" height='200px' src="Your_image_link" />`

2022-03-22 06:56 UTC, mayank-del commented on Web Development/Basic/NodeMailer/README.md
> +![Gmail](https://user-images.githubusercontent.com/82238106/159414755-b1c2909c-9090-4da8-ae0f-5fdc0dbdd5a3.jpg)
I reduced the size to 29kb ,it is 1/3 of original.

How we can apply html tags in readme.md??

2022-03-22 17:12 UTC, photon149 commented on Web Development/Basic/NodeMailer/README.md
> +![Gmail](https://user-images.githubusercontent.com/82238106/159414755-b1c2909c-9090-4da8-ae0f-5fdc0dbdd5a3.jpg)
@mayank-del by reducing the size he meant the size of the images , i.e. height and width in the README file ,  not the file size in KB

2022-03-22 17:30 UTC, mayank-del commented
now check @photon149  sir, i decrease dimension to 50%

2022-03-23 04:19 UTC, mayank-del commented
@photon149 , @Kushal997-das  please it

2022-03-23 04:21 UTC, Kushal997-das approved these changes
@mayank-del LGTM 💯

2022-03-23 04:21 UTC, Kushal997-das commented
@photon149 Have a look !

2022-03-24 12:59 UTC, photon149 commented
Looks fine to me.
@Kushal997-das It's good to merge .

2022-03-24 13:30 UTC, mayank-del commented
@photon149  yes yes ,it is good to merge

2022-03-25 14:57 UTC, photon149 approved these changes
Approved from my end.
@Kushal997-das

2022-03-26 17:12 UTC, merged