Graph Plotter App
Kushal997-das/Project-Guidance pull request #354
Opened 2022-03-08 06:46 UTC by Rahul2570089

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

- Yes , I have gone through it.

### Description

Fixes #281 Graph plotter app in flutter

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

2022-03-09 14:57 UTC, photon149 reviewed
@Rahul2570089 Great Work 👍🏻 
Just Add a section in your README regarding steps to run your app.
Everything else looks good to me.

2022-03-10 11:50 UTC, Rahul2570089 commented
I have already added the steps in my app's readme file. Do you mean to add in the readme file in "Mobile Applications" folder ?

2022-03-10 14:49 UTC, photon149 commented
@Rahul2570089 No it's fine.
@Kushal997-das @prakhar3062 have a look once.

2022-03-12 04:24 UTC, Kushal997-das requested changes
@Rahul2570089 Please delete all unwanted files only add those files those are really requires.

2022-03-12 05:54 UTC, Rahul2570089 commented
@Kushal997-das Sorry but can you please specify which files because according to me I have removed all files which are not required.

2022-03-13 11:44 UTC, Kushal997-das commented
@Rahul2570089 Just add your program files and using those you can run this project add them only and remaining files delete them , like your dot(.) files.

2022-03-13 15:57 UTC, Rahul2570089 commented
Okay

2022-03-13 16:06 UTC, Rahul2570089 commented
I have updated the pull request. Can you please check?

2022-03-13 16:50 UTC, Kushal997-das commented
> @Rahul2570089 Just add your program files and using those you can run this project add them only and remaining files delete them , like your dot(.) files.

??????

2022-03-13 16:54 UTC, Rahul2570089 commented
I have removed the dot(.) files

2022-03-13 16:56 UTC, Rahul2570089 commented
![Untitled](https://user-images.githubusercontent.com/76995136/158070337-f105d5a1-3c5f-4e78-86a9-7c1c690a86b9.png)

2022-03-16 05:32 UTC, Kushal997-das commented on Mobile Applications/Intermediate/graphplotter/README.md
> +
Can you please add here some words about your project .

2022-03-16 05:32 UTC, Kushal997-das commented on Mobile Applications/Intermediate/graphplotter/README.md
> +
@Rahul2570089

2022-03-16 05:50 UTC, Rahul2570089 commented on Mobile Applications/Intermediate/graphplotter/README.md
> +
Okay

2022-03-18 02:09 UTC, Kushal997-das approved these changes

2022-03-18 02:11 UTC, merged

2022-03-18 03:16 UTC, Rahul2570089 commented
Thank you ❤️