Clock desktop application added
Kushal997-das/Project-Guidance pull request #370
Opened 2022-03-09 07:28 UTC by Ash-KODES

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #issue_no

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2022-03-09 09:29 UTC, Ash-KODES commented
please review

2022-03-09 18:04 UTC, Ash-KODES commented
Sir,all the changes have been made except the project name.
I dont know how to change the name of a folder,please guide me?

2022-03-10 03:48 UTC, Kushal997-das commented on Desktop Application/Basic/Python/Desktop Clock/Readme.md
> +Digital Clock Application
Add a good gif or photos about your project in `readme.md` file.

2022-03-10 03:49 UTC, Kushal997-das commented
> Sir,all the changes have been made except the project name. I dont know how to change the name of a folder,please guide me?



> Sir,all the changes have been made except the project name. I dont know how to change the name of a folder,please guide me?

You can change your project name from local.

2022-03-12 08:09 UTC, Ash-KODES commented
Finally Done Sir :) Thankyou for  guidance!

2022-03-12 13:48 UTC, Kushal997-das requested changes
@Ash-KODES Can you please tell me what is that (.TTF) files if they are not related to your project then please delete them .

2022-03-12 14:09 UTC, Ash-KODES commented
> @Ash-KODES Can you please tell me what is that (.TTF) files if they are not related to your project then please delete them .

Yes,They are related to project,,Its the Icons that I used for my clock's UI.

2022-03-12 15:28 UTC, Kushal997-das commented
> > @Ash-KODES Can you please tell me what is that (.TTF) files if they are not related to your project then please delete them .
> 
> Yes,They are related to project,,Its the Icons that I used for my clock's UI.

Okey!!

2022-03-12 15:28 UTC, Kushal997-das approved these changes
@Ash-KODES 

LGTM 👍 

@photon149 please check !!

2022-03-13 08:41 UTC, photon149 commented
Approved from my end.
@prakhar3062 over to you.

2022-03-13 09:07 UTC, prakhar3062 approved these changes
okay from my end

2022-03-16 05:36 UTC, Kushal997-das approved these changes
@Ash-KODES Great 💯

2022-03-16 05:36 UTC, merged