Added MixChill(music player) files
Kushal997-das/Project-Guidance pull request #371
Opened 2022-03-09 07:56 UTC by Anchita15

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Yes, I have read..)

### Description

(MixChill is a music player that I have made in order comprise my top 5 favorite songs and this website have some amazing features like play, pause, auto, volume etc.
This website has been made using HTML, CSS and JavaScript.
This is responisve website.)

Fixes #358 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

<img width="960" alt="Screenshot 2022-03-01 143937" src="https://user-images.githubusercontent.com/83870242/157397260-f1682184-8d18-4b67-8d4d-cc60f80921b8.png">
<img width="960" alt="Screenshot 2022-03-01 144021" src="https://user-images.githubusercontent.com/83870242/157397268-7fe50751-72bc-4679-b3ba-18c6f150cfe4.png">

2022-03-10 04:00 UTC, Kushal997-das requested changes
@Anchita15 Everything looks fine except , it would be great if you add some gif or may be pictures in `readme.md` file .

And rename your project name `Mixchill` to `Micchill(Music player)` or something else so that anyone can understand what exactly inside .

2022-03-10 04:29 UTC, Anchita15 commented
> 

Okay I'll do the desired changes.

2022-03-10 04:30 UTC, Anchita15 commented
> @Anchita15 Everything looks fine except , it would be great if you add some gif or may be pictures in `readme.md` file .
> 
> And rename your project name `Mixchill` to `Micchill(Music player)` or something else so that anyone can understand what exactly inside .

Okay I'll do the desired changes.

2022-03-13 11:30 UTC, Kushal997-das commented
@Anchita15 Are you going to do the changes ? Or else your PR will close .

2022-03-14 10:25 UTC, Anchita15 commented
> @Anchita15 Are you going to do the changes ? Or else your PR will close .

I'll do it by today.

2022-03-14 11:11 UTC, Kushal997-das commented on Web Development/Basic/MixChill(Music_Player)/readme.md
> +   <img src="MixChill(Music_Player)/images/ss2.png"></a>
Both the links not working !

2022-03-14 11:11 UTC, Kushal997-das reviewed
@Anchita15 Links not working !

2022-03-14 14:30 UTC, Kushal997-das approved these changes
@Anchita15 Great 💯

2022-03-14 15:30 UTC, merged