MyOnlineMeals.com
Kushal997-das/Project-Guidance pull request #398
Opened 2022-03-12 16:26 UTC by Ayushi271

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #issue_no

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2022-03-13 08:43 UTC, photon149 commented
@Ayushi271 Please mention the issue number it fixes.

2022-03-13 12:36 UTC, Ayushi271 commented
This PR is for the issue #336

2022-03-13 12:38 UTC, Ayushi271 commented
Sorry for the late reply.
There were some issues with my laptop.

2022-03-14 01:59 UTC, photon149 commented
@Ayushi271 Great Project , but mention your issue number in your Pull Request Description , where it says "Fixes #Yourissuenum".
@prakhar3062 @Kushal997-das have a look.

2022-03-14 02:55 UTC, Kushal997-das requested changes
@Ayushi271 Everything is looks good, but you have to add gif or photos about your project in your `readme.md` file.

2022-03-14 19:27 UTC, Ayushi271 commented
@photon149  I have edited it and wrote issue no. Is it okay now?

2022-03-14 19:28 UTC, Ayushi271 commented
@Kushal997-das  I have added some images of the website in the readme.md file and also fixed some broken links. Is it okay now?

2022-03-15 04:00 UTC, Kushal997-das commented on Web Development/Basic/MyOnlineMeals/README.md
> +<img src="item page.png" >
@Ayushi271 Just reduce the image size.

2022-03-16 05:34 UTC, Kushal997-das commented on Web Development/Basic/MyOnlineMeals/README.md
> +<img src="item page.png" >
@Ayushi271

2022-03-17 04:00 UTC, Ayushi271 commented on Web Development/Basic/MyOnlineMeals/README.md
> +<img src="item page.png" >
@Kushal997-das  I have reduced the size of images.

2022-03-17 04:18 UTC, Kushal997-das commented on Web Development/Basic/MyOnlineMeals/README.md
> +##Service page
Give the space after `##` .

2022-03-17 04:20 UTC, Kushal997-das commented on Web Development/Basic/MyOnlineMeals/README.md
> +
Please use this structure to reduce the image size in `readme.md` file .

<img align="center"   width="602px" height='500px' src="Your_Image_location" />

You can reduce the width and height .

2022-03-18 02:25 UTC, Kushal997-das approved these changes
@Ayushi271 Great work !!

2022-03-18 02:25 UTC, Kushal997-das commented
@photon149 Have a look !!

2022-03-18 02:26 UTC, Kushal997-das commented
@prakhar3062 Have a look !

2022-03-18 02:31 UTC, photon149 reviewed
@Ayushi271 Approved from my end.

2022-03-19 03:24 UTC, merged

2022-03-20 18:24 UTC, Ayushi271 commented
@photon149 @Kushal997-das Thanks for guiding me and making my first contribution successful. Thanks for merging it.

2022-03-21 05:58 UTC, Kushal997-das commented
@Ayushi271 Most welcome , feel free to take another issue :)