Added Instagram Login Page Clone to Basic Web Development Project section
Kushal997-das/Project-Guidance pull request #401
Opened 2022-03-12 18:09 UTC by abhilipsasahoo03

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes. 

### Description

A simple Instagram App Official Login Page Clone built using HTML and CSS. [Here](https://www.instagram.com/accounts/login/?) is a reference to the official sign up/login page of Instagram for comparison.

Fixes #397 

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

2022-03-13 08:53 UTC, photon149 approved these changes
@abhilipsasahoo03 Good One !
@Kushal997-das @prakhar3062 have a look.

2022-03-13 09:11 UTC, prakhar3062 approved these changes

2022-03-14 03:00 UTC, Kushal997-das commented on Web Development/README.md
> +  - [Instagram Login Page Clone](https://abhilipsasahoo03.github.io/Instagram-Login-Page-Clone/)<br>
Change this link to your project location link see above work you can get idea.

2022-03-14 03:01 UTC, Kushal997-das requested changes
@abhilipsasahoo03 .

2022-03-14 04:36 UTC, abhilipsasahoo03 commented
Hi @Kushal997-das I've made the appropriate changes please look into it

2022-03-14 06:52 UTC, Kushal997-das approved these changes

2022-03-14 06:52 UTC, Kushal997-das commented
@abhilipsasahoo03 Great 💯

2022-03-14 06:53 UTC, merged

2022-04-07 03:40 UTC, Kushal997-das commented
@abhilipsasahoo03 We gonna remove the tag , just because you added same project in other repo.