Fixing the issue #390
Kushal997-das/Project-Guidance pull request #404
Opened 2022-03-14 03:47 UTC by Kranthi-Guribilli

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

(Write your answer here.)

Fixes #390 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2022-03-14 03:52 UTC, Kushal997-das commented on Desktop Application/Intermediate/C/PhoneBook_Management_System/README.md
> +![](https://github.com/Kranthi-Guribilli/Project-Guidance/blob/main/Desktop%20Application/Intermediate/C/PhoneBook_Management_System/Output_images/Op1.png)
Can you please reduce the image size ?

2022-03-14 03:53 UTC, Kushal997-das requested changes
@Kranthi-Guribilli Can you please reduce the image size those are mentioned in your `readme.md` file .

2022-03-14 05:06 UTC, Kranthi-Guribilli commented on Desktop Application/Intermediate/C/PhoneBook_Management_System/README.md
> +![](https://github.com/Kranthi-Guribilli/Project-Guidance/blob/main/Desktop%20Application/Intermediate/C/PhoneBook_Management_System/Output_images/Op1.png)
Yeah, has reduced the size. Please, kindly review it.

2022-03-16 05:52 UTC, Kushal997-das approved these changes

2022-03-16 05:52 UTC, Kushal997-das commented
@Photon149 Check !!

2022-03-18 02:27 UTC, merged