ping-pong-game
Kushal997-das/Project-Guidance pull request #405
Opened 2022-03-14 05:36 UTC by mayank-del

Description
This this basically a game which contains python turtle graphics

Fixes https://github.com/Kushal997-das/Project-Guidance/issues/329

Checklist
[ y] I've read the contribution guidelines.
[ y] I've checked the issue list before deciding what to submit.
[y ] I've edited the README.md and link to my code.
Related Issues or Pull Requests
NO issues , it is just a feature , I want to add.

2022-03-16 05:46 UTC, Kushal997-das requested changes
@mayank-del Your folder not in correct place , You folder location should be like this DesktopApplication/Python/Basic/Project_name.

2022-03-20 17:39 UTC, mayank-del commented
Sir, now i did whatever you told , i added it inside python of desktop application, now ,please accept it.

2022-03-21 05:52 UTC, Kushal997-das commented on Desktop Application/Basic/Python/Ping-pong-Python/Readme.md
> +##  Just open any code editor and go to main.py and click on run run button of your code editor, it will run succesfully
Frame the sentence correctly .

2022-03-21 05:54 UTC, Kushal997-das requested changes
@mayank-del Add gif of your project output in `readme.md` file . Make sure you do the changes soon , else we gonna close this PR as it's been more than 4days you were not responding , Do the changes by the EOD .

2022-03-22 03:18 UTC, closed without merging