project added
Kushal997-das/Project-Guidance pull request #406
Opened 2022-03-14 15:00 UTC by isha614

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes

Fixes #384

2022-03-16 14:08 UTC, photon149 approved these changes
Looks fine to me.Just rename your PR title to match your submission i.e. "TO-DO List"
@Kushal997-das @prakhar3062 have a look.

2022-03-18 02:14 UTC, Kushal997-das commented on Web Development/Basic/Sticky Notes/README.md
> +
@isha614 Reduce the image size .

2022-03-18 02:14 UTC, Kushal997-das requested changes
@isha614 Reduce the image size.

2022-03-19 07:16 UTC, Kushal997-das approved these changes

2022-03-19 07:18 UTC, merged