implemented a binary search algorithm with a comparison against naiv…
Kushal997-das/Project-Guidance pull request #408
Opened 2022-03-14 15:45 UTC by FatimahAdwan

…e search timing

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #issue_no

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2022-03-18 02:41 UTC, Kushal997-das requested changes
@FatimahAdwan 
 Do the requires changes !
1. Fix your `readme.md` file.
2. Add gif or photos about your project in `readme.md` file.

2022-03-22 21:30 UTC, FatimahAdwan commented
> @FatimahAdwan Do the requires changes !
> 
> 1. Fix your `readme.md` file.
> 2. Add gif or photos about your project in `readme.md` file.

okay, am on it

2022-03-30 20:17 UTC, FatimahAdwan commented
Hey kushal, it's me again, so I have been working on this since yesterday, atleast am able to push my updated readme for this project, pls help me check and do let me know

2022-03-31 08:00 UTC, Kushal997-das commented on Desktop Application/Basic/Python/Binary search/REAME.md
> +If the middle item is greater than the item, then the item is searched in the sub-array to the left of the middle item.
Delete this file .

2022-03-31 08:01 UTC, Kushal997-das requested changes
You didn't change anything inside this folder so please delete this `[Desktop Application/Basic/Python/Binary search/REAME.md`

2022-03-31 12:45 UTC, FatimahAdwan commented
> You didn't change anything inside this folder so please delete this `[Desktop Application/Basic/Python/Binary search/REAME.md`

i should delete it and put a new one?

2022-04-01 02:56 UTC, Kushal997-das reviewed
@FatimahAdwan You did changes in `[CONTRIBUTING.md]` file then you did you add other files as well please add only those files those are really changes by you .

@FatimahAdwan It's been so long still you are making mistake please make it correct or we gonna close this PR .

2022-04-01 03:07 UTC, Kushal997-das commented on Desktop Application/Basic/Python/Binary search/Readme.md
> +![Output Of Binary Search Algorithm](/C:\Users\Fati\Desktop.png).
Link is not working

2022-04-01 03:07 UTC, Kushal997-das requested changes
@FatimahAdwan Link is not working .

2022-04-01 15:21 UTC, FatimahAdwan commented
okay, I think is done now.

2022-04-05 19:46 UTC, FatimahAdwan commented
hi Kushal, am still waiting for you to check. thank you

2022-04-06 03:29 UTC, Kushal997-das reviewed
@FatimahAdwan This is a simple program not an any desktop application or project , we here at `project-guidance` only accept projects .

2022-04-06 03:30 UTC, closed without merging