Added cubic equation solver files
Kushal997-das/Project-Guidance pull request #427
Opened 2022-03-18 16:57 UTC by XZANATOL

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

- [x] Yes

### Description

Added a calculator that solves third degree equations (aX^3 + bX^2 + cX + d = 0) and is responsive on desktop and mobile devices.
Fixes #421 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

PR made under GSSoC'22 contributions.

2022-03-21 06:08 UTC, Kushal997-das commented on Web Development/Basic/Cubic_Equation_Solver/readme.md
> +A Calculator used to calculate Third degree equations.
ADD more lines about your project here .

2022-03-21 06:09 UTC, Kushal997-das requested changes
@XZANATOL Do the changes !

2022-03-26 17:47 UTC, prakhar3062 approved these changes
Nice work

2022-03-27 02:37 UTC, Kushal997-das approved these changes

2022-03-27 02:37 UTC, merged