Colorful Rain Effect Added
Kushal997-das/Project-Guidance pull request #445
Opened 2022-03-25 06:13 UTC by rajprem4214

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

### Description

A Colorful Rain Animation Effect Using HTML, CSS, JS.

Fixes #365 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

N/A

2022-03-25 15:01 UTC, photon149 requested changes
@rajprem4214 Add a README file with output SS.

2022-03-27 13:13 UTC, rajprem4214 commented
> @rajprem4214 Add a README file with output

Made required changes.

2022-03-28 02:40 UTC, Kushal997-das commented on Web Development/Basic/Colorful Rain Effect/.vscode/settings.json
> +}
Delete this file .

2022-03-28 02:41 UTC, Kushal997-das commented on Web Development/Basic/Colorful Rain Effect/readme.md
> +![preview](https://user-images.githubusercontent.com/85401522/156910556-a22eecf1-4251-42ed-97ba-02c410b59456.png)
Reduce the image size.

2022-03-28 02:41 UTC, Kushal997-das requested changes
@rajprem4214 Do the changes !

2022-03-28 11:47 UTC, rajprem4214 commented on Web Development/Basic/Colorful Rain Effect/readme.md
> +![preview](https://user-images.githubusercontent.com/85401522/156910556-a22eecf1-4251-42ed-97ba-02c410b59456.png)
> Reduce the image size.

done the same.

2022-04-01 05:49 UTC, rajprem4214 commented
> @rajprem4214 Do the changes !

made changes plz check

2022-04-02 09:46 UTC, rajprem4214 commented
> @rajprem4214 Do the changes !

@Kushal997-das  Made changes:  1. Reduced image size
                                                        2. Deleted Ignore File.

2022-04-02 14:29 UTC, Kushal997-das approved these changes
LGTM 👍 

@photon149 have a look !

2022-04-02 15:24 UTC, photon149 approved these changes
Approved from my end.

2022-04-02 16:09 UTC, prakhar3062 approved these changes

2022-04-03 16:34 UTC, merged