Budget App Added
Kushal997-das/Project-Guidance pull request #505
Opened 2022-04-07 15:23 UTC by Kunal0220

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes I have read the Contributing Guidelines.

### Description

1. This is a simple budget app which takes your monthly salary as input and your expenditure (in %) for different things.
2. Once we click on calculate , It will show a table with the amount of money you can spend on each item.
3. It will give an error if people spend more than they earn.

Fixes #274 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
issue #274 

[Contribution made under GSSoC 22']

Video Walkthrough:

https://user-images.githubusercontent.com/71934168/162234914-b33d1175-ce97-41e6-83b1-fa394965b049.mp4

2022-04-09 11:03 UTC, photon149 approved these changes
@Kunal0220 Well executed.
No duplicity ✅ 
Approved from my end.
@Kushal997-das take a look

2022-04-10 05:39 UTC, Kushal997-das commented on Web Development/Basic/Budgeting App/README.md
> +<img width="1385" alt="Screenshot 2022-04-02 at 12 04 44 AM" src="https://user-images.githubusercontent.com/71934168/161324569-912f458c-ba5e-4f88-b3cc-1f211d0d0347.png">
Reduce the width size to less than `700`

2022-04-10 05:39 UTC, Kushal997-das requested changes
@Kunal0220

2022-04-10 09:54 UTC, Kunal0220 commented
I made the change , Can you please review it once ?

2022-04-12 07:01 UTC, Kushal997-das approved these changes
@Kunal0220 Great work !

2022-04-12 07:13 UTC, merged