Added Desktop MP3 Player under Basic Python Desktop Application
Kushal997-das/Project-Guidance pull request #514
Opened 2022-04-10 06:44 UTC by abhilipsasahoo03

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes. 

### Description

- Added Desktop MP3 Player under Basic Python Desktop Application
- Made corresponding changes to README

Fixes #513 

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Screenshots

![149654407-d9bdd55f-78cf-404f-b152-3085480b9c7e](https://user-images.githubusercontent.com/80174214/162605899-e1157c16-2339-4236-9c4a-72a7a9b11440.png)
![149654409-9a109fb1-4845-4360-a320-8ef69852ee05](https://user-images.githubusercontent.com/80174214/162605901-c56b752c-8fd1-44e7-a073-678f71437457.png)
![149654415-9cf532d7-b385-4893-95e3-5c7d2948e324](https://user-images.githubusercontent.com/80174214/162605904-80a33a44-afa8-4f54-9c74-2304bfc3ad43.png)
![149654419-c3742cc4-2b2e-46c2-8f18-292040807352](https://user-images.githubusercontent.com/80174214/162605907-13f0a453-a50a-41d7-baaf-3d87d141511b.png)

2022-04-11 07:37 UTC, Kushal997-das commented on Desktop Application/Basic/Python/Desktop MP3 Player/README.md
> +![Screenshot (313)](https://user-images.githubusercontent.com/80174214/149654419-c3742cc4-2b2e-46c2-8f18-292040807352.png)
Please reduce the image size from this `readme.md` file .

2022-04-11 07:37 UTC, Kushal997-das requested changes
Do the requires changes @abhilipsasahoo03

2022-04-12 04:19 UTC, abhilipsasahoo03 commented
Hi @Kushal997-das I've made the required changes kindly look into it.

2022-04-12 06:48 UTC, Kushal997-das approved these changes
@photon149 have a look !

2022-04-13 15:37 UTC, abhilipsasahoo03 commented
Hey @Kushal997-das @photon149 kindly review my PR and if there's any change needed to be made, let me know

2022-04-14 02:40 UTC, Kushal997-das commented
> Hey @Kushal997-das @photon149 kindly review my PR and if there's any change needed to be made, let me know

@abhilipsasahoo03 It's under review only our mentor will review the PR and they will let you know .

2022-04-14 04:24 UTC, photon149 approved these changes
@abhilipsasahoo03 Everything seems perfect.
No Duplicity ✅ 
@Kushal997-das @prakhar3062 have a look

2022-04-14 06:51 UTC, prakhar3062 approved these changes

2022-04-14 11:26 UTC, merged