Command Line Emailer
Kushal997-das/Project-Guidance pull request #529
Opened 2022-04-14 05:34 UTC by devgirlcodes

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

I have read the contributing guidelines

### Description

The python app automates the task of sending emails via the command line. It's especially useful if you have to send the same email to more than one recipient.

Fixes #313 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

2022-04-14 13:14 UTC, photon149 reviewed
@devgirlcodes Nice Project. Just a minor change required , add output SS in your README file.
No Duplicity ✅

2022-04-15 13:39 UTC, devgirlcodes commented
> @devgirlcodes Nice Project. Just a minor change required , add output SS in your README file. No Duplicity ✅

I attached the screenshots in the readme. Could you have a look?

2022-04-16 08:58 UTC, photon149 approved these changes
Reviewed 👍🏻 
@Kushal997-das @prakhar3062 have a look

2022-04-19 03:19 UTC, Kushal997-das commented on Desktop Application/Basic/Python/cmd-line-emailer/readme.md
> +
Please reduce the width size of the all images .

2022-04-19 03:19 UTC, Kushal997-das requested changes
@devgirlcodes Do the requires changes .

2022-04-19 14:34 UTC, devgirlcodes commented on Desktop Application/Basic/Python/cmd-line-emailer/readme.md
> +
> @devgirlcodes Do the requires changes .

@Kushal997-das I have resized the images.

2022-04-20 05:28 UTC, devgirlcodes commented
> @devgirlcodes Do the requires changes .

I have made the requested changes.

2022-04-22 04:51 UTC, Kushal997-das approved these changes

2022-04-22 04:54 UTC, merged