Adding to-do app using Flask
Kushal997-das/Project-Guidance pull request #539
Opened 2022-04-16 16:25 UTC by muhammadgalhoum

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?

**yes**

### Description

**To-do app using Flask
You should install all requirements in the requirements.txt file before running the project 
You can take a view of this project's features in the README.md file of this project**

Fixes #issue_no #525 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2022-04-16 16:32 UTC, muhammadgalhoum commented
**I have tried to solve this problem #535, but I can't, so I have made this new pull request
Please review it @photon149**

2022-04-19 03:27 UTC, Kushal997-das commented on Web Development/Intermediate/To-do app/README.md
> +![Create New Task](Images/Add%20New%20Task.PNG)
Reduce the width .

2022-04-19 03:27 UTC, Kushal997-das commented on Web Development/Intermediate/To-do app/README.md
> +
@muhammadgalhoum

2022-04-19 03:27 UTC, Kushal997-das commented on Web Development/Intermediate/To-do app/README.md
> +
Reduce the width size .

2022-04-19 03:28 UTC, Kushal997-das requested changes
@muhammadgalhoum Do the requires changes .

2022-04-19 03:34 UTC, muhammadgalhoum commented
I did these spaces between the lines to avoid any errors or warnings in the README.md file
Do you want me to delete these spaces or what do you need? @Kushal997-das

2022-04-19 03:42 UTC, Kushal997-das commented
> I did these spaces between the lines to avoid any errors or warnings in the README.md file Do you want me to delete these spaces or what do you need? @Kushal997-das

No man just reduce the width size of the all images which are in your `readme.md` file .

2022-04-19 03:50 UTC, muhammadgalhoum commented
I took a complete page screenshot for each feature on my website to appear this feature clearly
Do you need me to crop each of the screenshots pages of my website to reduce its width?
@Kushal997-das

2022-04-19 03:58 UTC, Kushal997-das commented
> I took a complete page screenshot for each feature on my website to appear this feature clearly Do you need me to crop each of the screenshots pages of my website to reduce its width? @Kushal997-das

Don't you understand what is the meaning of width ? No need to crop you can reduce the width using HTML tags in the readme file . After all changes do comment here .

2022-04-19 04:17 UTC, muhammadgalhoum commented
I have used this way `![Login](screenshots/Login.PNG)` not this way` <img src="screenshots/Login.PNG" width="600px"/>`

See my new code changes and give me your opinion about these changes
@Kushal997-das

2022-04-19 04:23 UTC, Kushal997-das commented on Web Development/Intermediate/To-do app/README.md
> +### 6. Uncompleted Tasks page
Use this command to reduce image size .

`<img align="center" width="500px" height='300px' src="Paste your image URL" />

2022-04-19 04:23 UTC, Kushal997-das requested changes
@muhammadgalhoum

2022-04-19 04:24 UTC, muhammadgalhoum commented on Web Development/Intermediate/To-do app/README.md
> +### 6. Uncompleted Tasks page
As you like

2022-04-19 04:50 UTC, muhammadgalhoum commented
Can you please review it again @Kushal997-das

2022-04-19 05:00 UTC, muhammadgalhoum commented
@Kushal997-das 
When I have tried to use this command `<img align="center" width="500px" height='300px' src="Paste your image URL" />`most of the images became like the following image so I resize it using a special website and make the width 600px as you like

![Capture](https://user-images.githubusercontent.com/56798376/163923037-e05ae5ac-08f5-4b6e-b0af-e1d35a474dae.PNG)

2022-04-19 05:49 UTC, Kushal997-das commented
> @Kushal997-das When I have tried to use this command `<img align="center" width="500px" height='300px' src="Paste your image URL" />`most of the images became like the following image so I resize it using a special website and make the width 600px as you like
> 
> ![Capture](https://user-images.githubusercontent.com/56798376/163923037-e05ae5ac-08f5-4b6e-b0af-e1d35a474dae.PNG)

Man you should try yourself i gave you just idea how you can resize using HTML tags . Don't crop the image as you are going to reduce the size using HTML tag , so use only original image then use these tags . YOu can also try to change height and width of the image .

2022-04-19 05:53 UTC, muhammadgalhoum commented
Are you need all the screenshots to have the same width and height? @Kushal997-das

2022-04-19 15:29 UTC, muhammadgalhoum commented
Please review it again @Kushal997-das

2022-04-22 04:53 UTC, Kushal997-das requested changes
@muhammadgalhoum What should i review any of these links are not working in your `readme.md` file .

2022-04-22 12:58 UTC, muhammadgalhoum commented
You asked me to make all the pictures the same size and height and I did that
There is no error in the README.MD file
Therefore, I asked you to review the required changes
Where are the links that don't work?!
@Kushal997-das

2022-04-23 05:03 UTC, Kushal997-das commented
> You asked me to make all the pictures the same size and height and I did that There is no error in the README.MD file Therefore, I asked you to review the required changes Where are the links that don't work?! @Kushal997-das

![check](https://user-images.githubusercontent.com/61356005/164878509-64168bc8-76a7-4eb7-942a-9b24297c00c5.jpg)

2022-04-23 14:39 UTC, muhammadgalhoum commented
### Please review again @Kushal997-das

2022-04-24 04:23 UTC, Kushal997-das approved these changes
@photon149 Have a look .

2022-04-24 05:04 UTC, photon149 reviewed
@muhammadgalhoum Nicely Implemented , though just one small addition I would suggest is to add in your README file the steps to run your app .

2022-04-24 08:36 UTC, muhammadgalhoum commented
**Please review again @photon149 
Thanks in advanced**

2022-04-24 08:54 UTC, photon149 approved these changes
@muhammadgalhoum Great 👍🏻 
Approved from my end.
No Duplicity ✅ 
@Kushal997-das @prakhar3062 have a look

2022-04-24 18:39 UTC, prakhar3062 approved these changes

2022-04-25 04:16 UTC, merged