Added Naruto Website
Kushal997-das/Project-Guidance pull request #545
Opened 2022-04-17 07:33 UTC by Bhushan-Thombre

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

### Description

A simple website of Naruto. A completely responsive website made using React and styled components that also contain scroll animations implemented using ScrollReveal JavaScript library.

Fixes #534 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2022-04-19 13:47 UTC, Kushal997-das commented on Web Development/Intermediate/Naruto (React)/readme.md
> +<span>GitHub - </span><a href="https://github.com/Bhushan-Thombre">Click Here</a>
Please reduce the image size .

2022-04-19 13:48 UTC, Kushal997-das requested changes
@Bhushan-Thombre write your project name `Naruto` instead of `Naruto-React` Thanks .

2022-04-20 11:57 UTC, Bhushan-Thombre commented
I have made the necessary changes.

2022-04-22 04:56 UTC, Kushal997-das approved these changes
@photon149 have look .

2022-04-23 18:09 UTC, prakhar3062 approved these changes

2022-04-24 04:25 UTC, merged