Added Stock Market Project
Kushal997-das/Project-Guidance pull request #603
Opened 2022-05-01 11:57 UTC by Bhushan-Thombre

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

YES

### Description

Stock Market Web App that displays the basic stock information of a particular stock such as price, percent change in the stock value, previous close, 52 weeks high, etc.

Fixes #584 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2022-05-02 04:26 UTC, photon149 requested changes
@Bhushan-Thombre Please attach a README file to the same alongside output SS,

2022-05-02 14:31 UTC, Bhushan-Thombre commented
@photon149 The project already contains a README file with the output screenshots

2022-05-02 14:37 UTC, photon149 approved these changes
✔️ 
Approved from my end.
@Bhushan-Thombre just a suggestion , its better that you add all the images in a seperate folder.
@Kushal997-das

2022-05-03 08:45 UTC, prakhar3062 approved these changes

2022-05-06 05:27 UTC, Kushal997-das approved these changes

2022-05-06 05:27 UTC, merged