Voice app
Kushal997-das/Project-Guidance pull request #732
Opened 2022-05-25 16:34 UTC by utkarsh006

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ? 
Yes I have read the contributing guidelines.

### Description

Added Voice to text App in Kotlin

Fixes #702 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

https://user-images.githubusercontent.com/94545831/170314832-17e62efd-9d80-46b4-857c-b4a5023f6295.mp4

2022-05-28 05:31 UTC, photon149 requested changes
@utkarsh006 Project looks good , but also make a README file withn the VoicetoText folder as well

2022-05-28 15:59 UTC, utkarsh006 commented
@photon149 I've done the requested changes. Kindly merge the pr

2022-05-28 18:00 UTC, prakhar3062 approved these changes

2022-05-30 04:06 UTC, Kushal997-das approved these changes

2022-05-30 04:06 UTC, merged