Eth to Smart contract transaction
Kushal997-das/Project-Guidance pull request #769
Opened 2023-01-05 17:29 UTC by Sanitya7

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes

### Description

(Write your answer here.)

Fixes #767 

### Checklist

- [x ] I've read the contribution guidelines.
- [ x] I've checked the issue list before deciding what to submit.
- [ x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2023-01-06 15:41 UTC, Kushal997-das requested changes
Looks good But @Sanitya7 please try to add more description about your project.

2023-01-09 09:17 UTC, Sanitya7 commented
Hi @Kushal997-das , I have updated the documentation, you may check it 👍

2023-01-10 04:30 UTC, Kushal997-das approved these changes

2023-01-10 04:32 UTC, Kushal997-das commented
> Hi @Kushal997-das , I have updated the documentation, you may check it 👍

LGTM 👍🏻

2023-01-10 04:36 UTC, merged