Mobile App - Netflix Clone
Kushal997-das/Project-Guidance pull request #778
Opened 2023-01-08 08:18 UTC by himanshu240601

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes.

### Description
Hi, I want to contribute to this repo by adding a netflix clone app created using flutter. I put this app under mobile applications/intermediate

### Checklist

- [✓] I've read the contribution guidelines.
- [✓] I've checked the issue list before deciding what to submit.
- [✓] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2023-01-08 15:08 UTC, Kushal997-das commented
@himanshu240601 Please mention the issue number that you been solved .

2023-01-08 15:51 UTC, himanshu240601 commented
> @himanshu240601 Please mention the issue number that you been solved .

I've opened an issue, #779 
Kindly check and assign the same.

2023-01-10 04:55 UTC, Kushal997-das requested changes
@himanshu240601 Hello , Your `readme.md` file images are not loading please check it .
Also please try to remove those files those are not really important to this project .

2023-01-10 06:10 UTC, himanshu240601 commented
> @himanshu240601 Hello , Your `readme.md` file images are not loading please check it . Also please try to remove those files those are not really important to this project .

Hey!, I've made the following changes - 
- Updated the readme.md file in netflix_clone directory
- Added the netflix clone project link in the readme.md in mobile application directory (the link is for the main branch)
- Removed unnecessary files from my project (netflix_clone)

2023-01-11 03:36 UTC, Kushal997-das requested changes
Please fix the mentioned things .

2023-01-11 03:36 UTC, Kushal997-das commented on Mobile Applications/Intermediate/netflix_clone/README.md
> +
App screenshot are not working in `readme.md` file  [here](https://github.com/himanshu240601/Project-Guidance/blob/mobile-app-project-guidance/Mobile%20Applications/Intermediate/netflix_clone/README.md)

2023-01-11 05:41 UTC, himanshu240601 commented on Mobile Applications/Intermediate/netflix_clone/README.md
> +
I've checked the readme and it's working fine. All the screenshots are loading correctly.
![Screenshot 2023-01-11 110851](https://user-images.githubusercontent.com/95276862/211726557-48230506-c9fa-4294-9ebd-3a3c7a7bbe84.png)

2023-01-11 06:26 UTC, Kushal997-das commented on Mobile Applications/Intermediate/netflix_clone/README.md
> +
No , it's not [check this](https://github.com/himanshu240601/Project-Guidance/tree/mobile-app-project-guidance/Mobile%20Applications/Intermediate/netflix_clone)

2023-01-11 13:08 UTC, himanshu240601 commented on Mobile Applications/Intermediate/netflix_clone/README.md
> +
> No , it's not [check this](https://github.com/himanshu240601/Project-Guidance/tree/mobile-app-project-guidance/Mobile%20Applications/Intermediate/netflix_clone)

I've checked multiple times, there's nothing wrong. I don't know why the screenshots are not working on your side.
Should I remove these from the readme?

2023-01-11 13:33 UTC, Kushal997-das commented on Mobile Applications/Intermediate/netflix_clone/README.md
> +
No do not remove try to fix it . 

This is the [URL](https://github.com/himanshu240601/Project-Guidance/blob/mobile-app-project-guidance/Mobile%20Applications/Intermediate/netflix_clone/README.md) for same

2023-01-12 07:48 UTC, himanshu240601 commented on Mobile Applications/Intermediate/netflix_clone/README.md
> +
Hey! I've made some changes to the readme file. It should work now. Please check [here!](https://github.com/himanshu240601/Project-Guidance/tree/mobile-app-project-guidance/Mobile%20Applications/Intermediate/netflix_clone)

2023-01-12 16:10 UTC, Kushal997-das requested changes
@himanshu240601 Images are not loading .

2023-01-12 16:10 UTC, Kushal997-das commented on Mobile Applications/Intermediate/netflix_clone/README.md
> +</p>
![Image not loading](https://user-images.githubusercontent.com/61356005/212120009-b85ba463-26bd-4a5d-8426-74271aba4473.JPG)

2023-01-12 16:41 UTC, himanshu240601 commented on Mobile Applications/Intermediate/netflix_clone/README.md
> +</p>
> ![Image not loading](https://user-images.githubusercontent.com/61356005/212120009-b85ba463-26bd-4a5d-8426-74271aba4473.JPG)

try to check again now!
and if still not working could you please share the URL of the images that you're receiving

2023-01-13 03:12 UTC, merged

2023-01-13 05:07 UTC, himanshu240601 commented
great 👍