added Bean eater loader
Kushal997-das/Project-Guidance pull request #783
Opened 2023-01-10 08:11 UTC by muskan467

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes, I have read the Contributing guidelines.

### Description

Loader which is built in html and css.

Fixes #780 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2023-01-11 15:55 UTC, Kushal997-das approved these changes

2023-01-11 15:55 UTC, Kushal997-das requested changes
@muskan467 Hello Please try to deploy this project and add the link in `readme.md` file.

2023-01-12 13:38 UTC, muskan467 commented
@Kushal997-das Please check

2023-01-12 16:18 UTC, Kushal997-das approved these changes
LGTM 👍🏻

2023-01-12 16:19 UTC, merged