Gravity project added  issue #795
Kushal997-das/Project-Guidance pull request #798
Opened 2023-01-18 11:42 UTC by programmingninjas

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #795 

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2023-01-18 15:48 UTC, Kushal997-das commented
@programmingninjas Fill the from correctly .

> ### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
> (Write your answer here.)
> 
> ### Description
> (Write your answer here.)
> 
> Fixes #795
> 
> ### Checklist
> * [ ]  I've read the contribution guidelines.
> * [ ]  I've checked the issue list before deciding what to submit.
> * [ ]  I've edited the `README.md` and link to my code.
> 
> ## Related Issues or Pull Requests
> (Write your answer here.)

Write all the answer that has been asked .

2023-01-18 15:56 UTC, programmingninjas commented
@Kushal997-das sorry I updated the form please review now

2023-01-18 16:23 UTC, Kushal997-das requested changes
Fix the issues .

2023-01-18 16:23 UTC, Kushal997-das commented on Desktop Application/Basic/Python/Gravity/README.md
> +
Images are not loading Please check.

2023-01-18 16:37 UTC, programmingninjas commented
I changed the image link by adding your username instead of mine @Kushal997-das

2023-01-18 16:41 UTC, programmingninjas reviewed
link updated

2023-01-18 16:41 UTC, programmingninjas commented on Desktop Application/Basic/Python/Gravity/README.md
> +
link updated

2023-01-19 03:03 UTC, Kushal997-das commented
> I changed the image link by adding your username instead of mine @Kushal997-das

NO man this way you can't display the image . Try to fix it.

2023-01-19 03:03 UTC, Kushal997-das requested changes
Images are not working .

2023-01-19 10:56 UTC, programmingninjas commented
@Kushal997-das kindly check again now I uploaded the image in README.md

2023-01-19 14:38 UTC, Kushal997-das approved these changes
LGTM 💯

2023-01-19 14:40 UTC, merged