spotify clone added
Kushal997-das/Project-Guidance pull request #812
Opened 2023-01-22 14:22 UTC by Laraibnehal

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

yes
### Description

(Write your answer here.)

Fixes #766

### Checklist

- [x ] I've read the contribution guidelines.
- [x ] I've checked the issue list before deciding what to submit.
- [ x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2023-01-22 14:22 UTC, Laraibnehal commented
@Kushal997-das

2023-01-23 04:21 UTC, Kushal997-das requested changes
@Laraibnehal Add picture related to your project in `readme.md` file

2023-01-23 12:29 UTC, Laraibnehal commented
@Kushal997-das

2023-01-24 03:58 UTC, Kushal997-das requested changes
@Laraibnehal Add some description about your project  in readme.md file also try to add this project in basic folder .

2023-01-24 07:55 UTC, Laraibnehal commented
On it.

2023-01-25 08:02 UTC, Laraibnehal commented
Done @Kushal997-das

2023-01-25 16:30 UTC, Kushal997-das requested changes
Do the require changes .

2023-01-25 16:30 UTC, Kushal997-das commented on Web Development/Basic/Spotify clone/README.md
> +![Spotify - Your favourite music is here - Google Chrome 1_5_2023 11_14_28 AM](https://user-images.githubusercontent.com/95610027/214508475-e46e6d43-5d7f-4141-beab-8b361d67b897.png)
No to good description . Write in a professional way .

2023-01-25 18:50 UTC, Laraibnehal commented on Web Development/Basic/Spotify clone/README.md
> +![Spotify - Your favourite music is here - Google Chrome 1_5_2023 11_14_28 AM](https://user-images.githubusercontent.com/95610027/214508475-e46e6d43-5d7f-4141-beab-8b361d67b897.png)
Ok

2023-01-29 17:02 UTC, Kushal997-das requested changes
Change the description like this description seems like casual please see other project from my repo and understand how to write a good description about your project .

2023-01-29 17:02 UTC, Kushal997-das commented on Web Development/Basic/Spotify clone/README.md
> +![Spotify - Your favourite music is here - Google Chrome 1_5_2023 11_14_28 AM](https://user-images.githubusercontent.com/95610027/214508475-e46e6d43-5d7f-4141-beab-8b361d67b897.png)
Change the description like this description seems like casual please see other project from my repo and understand how to write a good description about your project .

2023-02-22 15:41 UTC, closed without merging