added AI readme
Kushal997-das/Project-Guidance pull request #821
Opened 2023-01-26 12:14 UTC by muskan467

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md)?

Yes, I have read the Contributing guidelines.

### Description

I have made the AI readme.

Fixes #814 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#814

2023-01-26 16:14 UTC, muskan467 commented
Kindly merge it @Kushal997-das

2023-01-27 06:36 UTC, Kushal997-das requested changes
@muskan467 Do the changes .

2023-01-27 06:36 UTC, Kushal997-das commented on Artificial Intelligence/README.md
> +<p align="right"><a href="#Bottom"><img src="https://img.shields.io/badge/-Bottom-red?style=for-the-badge" /></a></p>
@muskan467 Reduce the width and height of the image . Make it a small image .

2023-01-27 14:39 UTC, Kushal997-das approved these changes
@muskan467 Great work

2023-01-27 14:39 UTC, merged