Service providing Website added
Kushal997-das/Project-Guidance pull request #838
Opened 2023-01-31 12:08 UTC by charu1603

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Yes)

### Description

(Write your answer here.)

Fixes #836

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2023-01-31 15:35 UTC, Kushal997-das requested changes
@charu1603 These things you need to change - 

1. Add images about your project in the `readme.md` section .
2.  Deploy this project and add the deployment link in `readme.md` file .

2023-02-01 04:08 UTC, Kushal997-das requested changes
@charu1603  Images are not loading in your `readme.md` file .

2023-02-01 10:54 UTC, charu1603 commented
I have done the suggested changes

2023-02-01 18:13 UTC, charu1603 commented
Done sir

2023-02-02 03:26 UTC, Kushal997-das requested changes
@charu1603 Do the requires changes without making errors then i'll merge your PR

2023-02-02 03:26 UTC, Kushal997-das commented on Web Development/README.md
> +| 13. | [To-do App](https://github.com/Kushal997-das/Project-Guidance/tree/main/Web%20Development/Intermediate/To-do%20app) | 14. | [Tourism Management System](https://github.com/Kushal997-das/Projec
This needs to add under basic portion and please see there all the things has been written in alphabetical order so since your project name starts with the letter `S` then you have to check same way , i think in basic section this project should be add in 41 number .

2023-02-03 03:32 UTC, Kushal997-das approved these changes
@charu1603  Great work 💯

2023-02-03 03:35 UTC, merged