Pomodoro-Timer using Js
Kushal997-das/Project-Guidance pull request #867
Opened 2023-02-26 17:50 UTC by Devang2304

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

A Simple Pomodoro Timer  with progress bar changes as time decreases.Created using HTML, CSS and JavaScript. 
you can View a demo

Fixes #865 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #865

2023-02-26 17:56 UTC, Devang2304 commented
@Kushal997-das sorry for creating another pull request I am new to OpenSource Contribution, I have made all the required changes you requested in previous issue #865 , you can check and merge the project. Thanks for giving me opportunity

2023-02-28 17:20 UTC, Kushal997-das requested changes
@Devang2304 Your images are not loading in `readme.md` file also make sure you add project in in alphabetical order in `web development/readme.md` file . 

Note : No dot create new PR just update the mentioned things in this PR only.

2023-03-01 18:31 UTC, Devang2304 commented
@Kushal997-das image issue fixed and added my project according to the aphabetical order. Ready to merge now

2023-03-04 11:24 UTC, Kushal997-das approved these changes

2023-03-04 11:25 UTC, merged