Add Airbnb EDA Analysis in Machine Learning Folder
Kushal997-das/Project-Guidance pull request #926
Opened 2023-10-08 13:15 UTC by aneeshd27

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

### Description

(Write your answer here.)

Fixes #issue_no

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

2023-10-12 15:57 UTC, Kushal997-das requested changes
@aneeshd27 Hello, follow the guidelines for better understanding. Add a readme.md file add all the details there. Follow another project to understand it better.

2023-10-13 06:07 UTC, Kushal997-das commented on Machine Learning and Data Science/Basic/Airbnb EDA Analysis/README.md
> +
Inappropriate file  why this is empty

2023-10-13 07:53 UTC, aneeshd27 commented on Machine Learning and Data Science/Basic/Airbnb EDA Analysis/README.md
> +
Added important content in README.md file with proper indent

2023-10-14 04:16 UTC, Kushal997-das approved these changes

2023-10-14 04:18 UTC, merged