Hangman game added
Kushal997-das/Project-Guidance pull request #939
Opened 2023-10-14 16:37 UTC by rittikadeb

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

Yes

### Description

Added a fun and educational Hangman Game.

Fixes #937 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

No

2023-10-16 09:22 UTC, Kushal997-das requested changes
@rittikadeb Changes the below things: 

1.  Deploy the project and add the deploy link in `readme.md` file .
2.  Add the project name and count in the web development `readme.md` file.

2023-10-16 15:02 UTC, rittikadeb commented
This project is under Haktoberfest 2023.

2023-10-17 04:38 UTC, Kushal997-das commented on Web Development/README.md
> +| 22. | [Google Clone](https://github.com/SamarpanCoder2002/Project-Guidance/tree/main/Web%20Development/Basic/Google%20Clone) | 23. | [Google Homepage Clone](https://github.com/rajprem4214/Project-G
25 number is missing , kindly check

2023-10-18 18:19 UTC, rittikadeb commented
@Kushal997-das pls review it

2023-10-19 05:33 UTC, Kushal997-das approved these changes

2023-10-19 05:37 UTC, merged