Gssoc 24v wanna add my project via #971
Kushal997-das/Project-Guidance pull request #972
Opened 2024-05-10 16:46 UTC by ramsatyasai

### Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?
yes
(Write your answer here.)

### Description
the project description is that if we upload the attendance sheet which include the time duration in the virtual class , students list with rolls, and the minimum threshold percentage of class duration attended. the sorted list of students will be displays. technologies used python libs like flask for backend, pandas for data analysis, etc
(Write your answer here.)

Fixes #971 

### Checklist

- [. ] I've read the contribution guidelines.
- [. ] I've checked the issue list before deciding what to submit.
- [. ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
please add Gssoc tags to the issue before merging the pull request 
(Write your answer here.)

2024-05-12 13:56 UTC, Kushal997-das requested changes
@ramsatyasai Add a good `readme.md` file where you explain about your project and makesure add the deploy link of the project.

2024-05-13 18:05 UTC, ramsatyasai commented
done the changes required can you please verify and merge the pull request

2024-05-15 02:06 UTC, Kushal997-das requested changes
@ramsatyasai Yet it not full fill the requirement , as i mentioned you need to host your website and add the deploy link here in `readme.md` file.

2024-05-15 08:20 UTC, ramsatyasai commented
once check it sir just deployed the application

2024-05-16 03:03 UTC, Kushal997-das requested changes
@ramsatyasai Kindly fix all these then say you complete not before .

2024-05-16 03:03 UTC, Kushal997-das commented on Web Development/Basic/virtual-classes-attendance-automation-system/readme.md
> +
The site is not loading , better to deploy platform like `netlify` or `github-pages`.

2024-05-16 03:17 UTC, ramsatyasai commented on Web Development/Basic/virtual-classes-attendance-automation-system/readme.md
> +
https://github.com/Kushal997-das/Project-Guidance/assets/108385414/8522a05d-6984-4326-9cde-fb81351d47f4

Before updating you the changes I have checked it twice. Maybe some network issue on ur side. The link is working fine even I have confirmed it with my friends.

2024-05-16 03:38 UTC, Kushal997-das requested changes
Okey! Now add your project name [here](https://github.com/Kushal997-das/Project-Guidance/blob/main/Web%20Development/README.md) alpha format .

I'll check it later.

2024-05-17 07:18 UTC, ramsatyasai commented
done

2024-05-17 13:38 UTC, Kushal997-das approved these changes
@ramsatyasai 💯

2024-05-17 13:47 UTC, merged